use_frameworks!

platform :ios, '9.0'

target 'WDAutoTrackSolutionKit_Example' do
  pod 'WDAutoTrackSolutionKit', :path => '../'

  target 'WDAutoTrackSolutionKit_Tests' do
    inherit! :search_paths

    
  end
end
